
/*
Auto-generated by CVXPYgen on October 12, 2025 at 16:20:31.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_lambda_cost(0.00000000000000000000);
  cpg_update_x_curr(0.97457513696789466184);
  cpg_update_k_gain(0.06212074286607434381);
  cpg_update_x_ref(-0.81387325738502636074);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  printf("u = %f\n", CPG_Result.prim->u);

  // Print dual solution
  printf("d0 = %f\n", CPG_Result.dual->d0);
  printf("d1 = %f\n", CPG_Result.dual->d1);

  return 0;

}
