
/*
Auto-generated by CVXPYgen on October 12, 2025 at 16:20:31.
Content: Declarations for Python binding with pybind11.
*/

// User-defined parameters
struct CPG_Params_cpp_t {
    double lambda_cost;
    double x_curr;
    double k_gain;
    double x_ref;
};

// Flags for updated user-defined parameters
struct CPG_Updated_cpp_t {
    bool lambda_cost;
    bool x_curr;
    bool k_gain;
    bool x_ref;
};

// Primal solution
struct CPG_Prim_cpp_t {
    double u;
};

// Dual solution
struct CPG_Dual_cpp_t {
    double d0;
    double d1;
};

// Solver information
struct CPG_Info_cpp_t {
    double obj_val;
    int iter;
    char* status;
    double pri_res;
    double dua_res;
    double time;
};

// Solution and solver information
struct CPG_Result_cpp_t {
    CPG_Prim_cpp_t prim;
    CPG_Dual_cpp_t dual;
    CPG_Info_cpp_t info;
};

// Main solve function
CPG_Result_cpp_t solve_cpp(struct CPG_Updated_cpp_t& CPG_Updated_cpp, struct CPG_Params_cpp_t& CPG_Params_cpp);
