
/*
Auto-generated by CVXPYgen on October 12, 2025 at 16:20:31.
Content: Python binding with pybind11.
*/

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <ctime>
#include <chrono>
#include "cpg_module.hpp"

extern "C" {
    #include "include/cpg_workspace.h"
    #include "include/cpg_solve.h"
}

namespace py = pybind11;

CPG_Result_cpp_t solve_cpp(struct CPG_Updated_cpp_t& CPG_Updated_cpp, struct CPG_Params_cpp_t& CPG_Params_cpp){

    // Pass changed user-defined parameter values to the solver
    if (CPG_Updated_cpp.lambda_cost) {
        cpg_update_lambda_cost(CPG_Params_cpp.lambda_cost);
    }
    if (CPG_Updated_cpp.x_curr) {
        cpg_update_x_curr(CPG_Params_cpp.x_curr);
    }
    if (CPG_Updated_cpp.k_gain) {
        cpg_update_k_gain(CPG_Params_cpp.k_gain);
    }
    if (CPG_Updated_cpp.x_ref) {
        cpg_update_x_ref(CPG_Params_cpp.x_ref);
    }

    // Solve
    auto ASA_start = std::chrono::high_resolution_clock::now();
    cpg_solve();
    auto ASA_end = std::chrono::high_resolution_clock::now();

    // Arrange and return results
    CPG_Prim_cpp_t CPG_Prim_cpp {};
    CPG_Prim_cpp.u = CPG_Prim.u;
    CPG_Dual_cpp_t CPG_Dual_cpp {};
    CPG_Dual_cpp.d0 = CPG_Dual.d0;
    CPG_Dual_cpp.d1 = CPG_Dual.d1;
    CPG_Info_cpp_t CPG_Info_cpp {};
    CPG_Info_cpp.obj_val = CPG_Info.obj_val;
    CPG_Info_cpp.iter = CPG_Info.iter;
    CPG_Info_cpp.status = CPG_Info.status;
    CPG_Info_cpp.pri_res = CPG_Info.pri_res;
    CPG_Info_cpp.dua_res = CPG_Info.dua_res;
    std::chrono::duration<double> elapsed = ASA_end - ASA_start;
    CPG_Info_cpp.time = elapsed.count();
    CPG_Result_cpp_t CPG_Result_cpp {};
    CPG_Result_cpp.prim = CPG_Prim_cpp;
    CPG_Result_cpp.dual = CPG_Dual_cpp;
    CPG_Result_cpp.info = CPG_Info_cpp;
    return CPG_Result_cpp;

}

PYBIND11_MODULE(cpg_module, m) {

    py::class_<CPG_Params_cpp_t>(m, "cpg_params")
            .def(py::init<>())
            .def_readwrite("lambda_cost", &CPG_Params_cpp_t::lambda_cost)
            .def_readwrite("x_curr", &CPG_Params_cpp_t::x_curr)
            .def_readwrite("k_gain", &CPG_Params_cpp_t::k_gain)
            .def_readwrite("x_ref", &CPG_Params_cpp_t::x_ref)
            ;

    py::class_<CPG_Updated_cpp_t>(m, "cpg_updated")
            .def(py::init<>())
            .def_readwrite("lambda_cost", &CPG_Updated_cpp_t::lambda_cost)
            .def_readwrite("x_curr", &CPG_Updated_cpp_t::x_curr)
            .def_readwrite("k_gain", &CPG_Updated_cpp_t::k_gain)
            .def_readwrite("x_ref", &CPG_Updated_cpp_t::x_ref)
            ;

    py::class_<CPG_Prim_cpp_t>(m, "cpg_prim")
            .def(py::init<>())
            .def_readwrite("u", &CPG_Prim_cpp_t::u)
            ;

    py::class_<CPG_Dual_cpp_t>(m, "cpg_dual")
            .def(py::init<>())
            .def_readwrite("d0", &CPG_Dual_cpp_t::d0)
            .def_readwrite("d1", &CPG_Dual_cpp_t::d1)
            ;

    py::class_<CPG_Info_cpp_t>(m, "cpg_info")
            .def(py::init<>())
            .def_readwrite("obj_val", &CPG_Info_cpp_t::obj_val)
            .def_readwrite("iter", &CPG_Info_cpp_t::iter)
            .def_readwrite("status", &CPG_Info_cpp_t::status)
            .def_readwrite("pri_res", &CPG_Info_cpp_t::pri_res)
            .def_readwrite("dua_res", &CPG_Info_cpp_t::dua_res)
            .def_readwrite("time", &CPG_Info_cpp_t::time)
            ;

    py::class_<CPG_Result_cpp_t>(m, "cpg_result")
            .def(py::init<>())
            .def_readwrite("cpg_prim", &CPG_Result_cpp_t::prim)
            .def_readwrite("cpg_dual", &CPG_Result_cpp_t::dual)
            .def_readwrite("cpg_info", &CPG_Result_cpp_t::info)
            ;

    m.def("solve", &solve_cpp);

    m.def("set_solver_default_settings", &cpg_set_solver_default_settings);
    m.def("set_solver_normalize", &cpg_set_solver_normalize);
    m.def("set_solver_scale", &cpg_set_solver_scale);
    m.def("set_solver_adaptive_scale", &cpg_set_solver_adaptive_scale);
    m.def("set_solver_rho_x", &cpg_set_solver_rho_x);
    m.def("set_solver_max_iters", &cpg_set_solver_max_iters);
    m.def("set_solver_eps_abs", &cpg_set_solver_eps_abs);
    m.def("set_solver_eps_rel", &cpg_set_solver_eps_rel);
    m.def("set_solver_eps_infeas", &cpg_set_solver_eps_infeas);
    m.def("set_solver_alpha", &cpg_set_solver_alpha);
    m.def("set_solver_time_limit_secs", &cpg_set_solver_time_limit_secs);
    m.def("set_solver_verbose", &cpg_set_solver_verbose);
    m.def("set_solver_warm_start", &cpg_set_solver_warm_start);
    m.def("set_solver_acceleration_lookback", &cpg_set_solver_acceleration_lookback);
    m.def("set_solver_acceleration_interval", &cpg_set_solver_acceleration_interval);
    m.def("set_solver_write_data_filename", &cpg_set_solver_write_data_filename);
    m.def("set_solver_log_csv_filename", &cpg_set_solver_log_csv_filename);

}
